// <auto-generated />
using System;
using BaiTapThucTapBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaiTapThucTapBackend.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    [Migration("20260505072005_Fix_XNKNhapKhoDetail")]
    partial class Fix_XNKNhapKhoDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaiTapThucTapBackend.Models.DonViTinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten_Don_Vi_Tinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Ten_Don_Vi_Tinh")
                        .IsUnique();

                    b.ToTable("DonViTinhs");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.Kho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten_Kho")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Ten_Kho")
                        .IsUnique();

                    b.ToTable("Khos");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.KhoUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kho_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ma_Dang_Nhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Kho_ID");

                    b.HasIndex("Ma_Dang_Nhap", "Kho_ID")
                        .IsUnique();

                    b.ToTable("KhoUsers");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma_LSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ten_LSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Ma_LSP")
                        .IsUnique();

                    b.HasIndex("Ten_LSP")
                        .IsUnique();

                    b.ToTable("LoaiSanPhams");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.NhaCungCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma_NCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten_NCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Ten_NCC")
                        .IsUnique();

                    b.ToTable("NhaCungCaps");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.NhapKho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kho_ID")
                        .HasColumnType("int");

                    b.Property<int>("NCC_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay_Nhap_Kho")
                        .HasColumnType("datetime2");

                    b.Property<string>("So_Phieu_Nhap_Kho")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Kho_ID");

                    b.HasIndex("NCC_ID");

                    b.HasIndex("So_Phieu_Nhap_Kho")
                        .IsUnique();

                    b.ToTable("NhapKhos");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.NhapKhoDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Don_Gia_Nhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Nhap_Kho_ID")
                        .HasColumnType("int");

                    b.Property<int>("SL_Nhap")
                        .HasColumnType("int");

                    b.Property<int>("San_Pham_ID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nhap_Kho_ID");

                    b.HasIndex("San_Pham_ID");

                    b.ToTable("NhapKhoChiTiets");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Don_Vi_Tinh_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Loai_San_Pham_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ma_San_Pham")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ten_San_Pham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Don_Vi_Tinh_ID");

                    b.HasIndex("Loai_San_Pham_ID");

                    b.HasIndex("Ma_San_Pham")
                        .IsUnique();

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.XNKNhapKho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kho_ID")
                        .HasColumnType("int");

                    b.Property<int>("NCC_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay_Nhap_Kho")
                        .HasColumnType("datetime2");

                    b.Property<string>("So_Phieu_Nhap_Kho")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Kho_ID");

                    b.HasIndex("NCC_ID");

                    b.HasIndex("So_Phieu_Nhap_Kho")
                        .IsUnique();

                    b.ToTable("XNKNhapKhos");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.XNKNhapKhoDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Don_Gia_Nhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SL_Nhap")
                        .HasColumnType("int");

                    b.Property<int>("San_Pham_ID")
                        .HasColumnType("int");

                    b.Property<int>("XNKNhap_Kho_ID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("San_Pham_ID");

                    b.HasIndex("XNKNhap_Kho_ID");

                    b.ToTable("XNKNhapKhoChiTiets");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.XuatKho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kho_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay_Xuat_Kho")
                        .HasColumnType("datetime2");

                    b.Property<string>("So_Phieu_Xuat_Kho")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Kho_ID");

                    b.HasIndex("So_Phieu_Xuat_Kho")
                        .IsUnique();

                    b.ToTable("XuatKhos");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.XuatKhoDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Don_Gia_Xuat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SL_Xuat")
                        .HasColumnType("int");

                    b.Property<int>("San_Pham_ID")
                        .HasColumnType("int");

                    b.Property<int>("Xuat_Kho_ID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("San_Pham_ID");

                    b.HasIndex("Xuat_Kho_ID");

                    b.ToTable("XuatKhoChiTiets");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.KhoUser", b =>
                {
                    b.HasOne("BaiTapThucTapBackend.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("Kho_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kho");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.NhapKho", b =>
                {
                    b.HasOne("BaiTapThucTapBackend.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("Kho_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaiTapThucTapBackend.Models.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("NCC_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kho");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.NhapKhoDetail", b =>
                {
                    b.HasOne("BaiTapThucTapBackend.Models.NhapKho", "NhapKho")
                        .WithMany("ChiTiets")
                        .HasForeignKey("Nhap_Kho_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaiTapThucTapBackend.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("San_Pham_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhapKho");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.SanPham", b =>
                {
                    b.HasOne("BaiTapThucTapBackend.Models.DonViTinh", "DonViTinh")
                        .WithMany()
                        .HasForeignKey("Don_Vi_Tinh_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaiTapThucTapBackend.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany("SanPhams")
                        .HasForeignKey("Loai_San_Pham_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonViTinh");

                    b.Navigation("LoaiSanPham");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.XNKNhapKho", b =>
                {
                    b.HasOne("BaiTapThucTapBackend.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("Kho_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaiTapThucTapBackend.Models.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("NCC_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kho");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.XNKNhapKhoDetail", b =>
                {
                    b.HasOne("BaiTapThucTapBackend.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("San_Pham_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaiTapThucTapBackend.Models.XNKNhapKho", "XNKNhapKho")
                        .WithMany("ChiTiets")
                        .HasForeignKey("XNKNhap_Kho_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("XNKNhapKho");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.XuatKho", b =>
                {
                    b.HasOne("BaiTapThucTapBackend.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("Kho_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kho");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.XuatKhoDetail", b =>
                {
                    b.HasOne("BaiTapThucTapBackend.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("San_Pham_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaiTapThucTapBackend.Models.XuatKho", "XuatKho")
                        .WithMany("ChiTiets")
                        .HasForeignKey("Xuat_Kho_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("XuatKho");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.NhapKho", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.XNKNhapKho", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.XuatKho", b =>
                {
                    b.Navigation("ChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
