// <auto-generated />
using System;
using BaiTapThucTapBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaiTapThucTapBackend.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    [Migration("20260429101140_AddForeignKey")]
    partial class AddForeignKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaiTapThucTapBackend.Models.DonViTinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten_Don_Vi_Tinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Ten_Don_Vi_Tinh")
                        .IsUnique();

                    b.ToTable("DonViTinhs");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.Kho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten_Kho")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Ten_Kho")
                        .IsUnique();

                    b.ToTable("Khos");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.KhoUser", b =>
                {
                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.Property<int>("Kho_ID")
                        .HasColumnType("int");

                    b.HasKey("User_ID", "Kho_ID");

                    b.HasIndex("Kho_ID");

                    b.ToTable("KhoUsers");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma_LSP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ten_LSP")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Ma_LSP")
                        .IsUnique()
                        .HasFilter("[Ma_LSP] IS NOT NULL");

                    b.HasIndex("Ten_LSP")
                        .IsUnique()
                        .HasFilter("[Ten_LSP] IS NOT NULL");

                    b.ToTable("LoaiSanPhams");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.NhaCungCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma_NCC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ten_NCC")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Ma_NCC")
                        .IsUnique()
                        .HasFilter("[Ma_NCC] IS NOT NULL");

                    b.HasIndex("Ten_NCC")
                        .IsUnique()
                        .HasFilter("[Ten_NCC] IS NOT NULL");

                    b.ToTable("NhaCungCaps");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.NhapKho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kho_ID")
                        .HasColumnType("int");

                    b.Property<int>("NCC_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay_Nhap_Kho")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NhaCungCap_ID")
                        .HasColumnType("int");

                    b.Property<string>("So_Phieu_Nhap_Kho")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Kho_ID");

                    b.HasIndex("NhaCungCap_ID");

                    b.HasIndex("So_Phieu_Nhap_Kho")
                        .IsUnique()
                        .HasFilter("[So_Phieu_Nhap_Kho] IS NOT NULL");

                    b.ToTable("NhapKhos");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.NhapKhoDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Don_Gia_Nhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Nhap_Kho_ID")
                        .HasColumnType("int");

                    b.Property<int>("SL_Nhap")
                        .HasColumnType("int");

                    b.Property<int>("San_Pham_ID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nhap_Kho_ID");

                    b.HasIndex("San_Pham_ID");

                    b.ToTable("NhapKhoDetail");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Don_Vi_Tinh_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Loai_San_Pham_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ma_San_Pham")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ten_San_Pham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Don_Vi_Tinh_ID");

                    b.HasIndex("Loai_San_Pham_ID");

                    b.HasIndex("Ma_San_Pham")
                        .IsUnique();

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ma_Dang_Nhap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mat_Khau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.KhoUser", b =>
                {
                    b.HasOne("BaiTapThucTapBackend.Models.Kho", "Kho")
                        .WithMany("KhoUsers")
                        .HasForeignKey("Kho_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaiTapThucTapBackend.Models.User", "User")
                        .WithMany("KhoUsers")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kho");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.NhapKho", b =>
                {
                    b.HasOne("BaiTapThucTapBackend.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("Kho_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaiTapThucTapBackend.Models.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("NhaCungCap_ID");

                    b.Navigation("Kho");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.NhapKhoDetail", b =>
                {
                    b.HasOne("BaiTapThucTapBackend.Models.NhapKho", "NhapKho")
                        .WithMany("Details")
                        .HasForeignKey("Nhap_Kho_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaiTapThucTapBackend.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("San_Pham_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhapKho");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.SanPham", b =>
                {
                    b.HasOne("BaiTapThucTapBackend.Models.DonViTinh", "DonViTinh")
                        .WithMany()
                        .HasForeignKey("Don_Vi_Tinh_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaiTapThucTapBackend.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany()
                        .HasForeignKey("Loai_San_Pham_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonViTinh");

                    b.Navigation("LoaiSanPham");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.Kho", b =>
                {
                    b.Navigation("KhoUsers");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.NhapKho", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("BaiTapThucTapBackend.Models.User", b =>
                {
                    b.Navigation("KhoUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
